### PR TITLE
add: fetch then loop comments

### PR DESCRIPTION
**Pull request by Knm24**
const getData = async () => {
    try {
        // https://api.stackexchange.com/docs/advanced-search#order=desc&sort=activity&title=next.js&filter=!6WPIomqlomSf5&site=stackoverflow&run=true
      const response = await fetch('https://api.stackexchange.com/2.3/search/advanced?order=desc&sort=activity&site=stackoverflow');

      if(!response.ok){
        throw new Error("Failed to fetch");
      }
      const data = await response.json();
      return data.items; 

    } catch (error) {
      console.error('Error fetching:', error);
    }
  };

### CODE REVIEW

**Comment by Knm24** [comment]
team pls review

**Comment by Knm24** [comment]
try to use fetch

**Comment by Knm24** [comment]
pls approve

**Review by Kanskii — APPROVED** [review]
ok

**Pull request merged**
